---
apeVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
  labels:
    app: boardgame
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: boardgame  
  template:
    metadata:
      labels:
        app: boardgame  
    spec:
      containers: 
      - name: boardgame
        image: devopsproject1.azurecr.io/boardgame:latest
        ports:
        - containerPort: 8080 
         
...